user:
  maximum_name: 50
  maximum_email: 255
  minimum_password: 6
  page_user: 10
post:
  maximum_title: 255
  page_post: 10
  picture_default: "post.jpg"
tag:
  maximum_name: 50
  page_tag: 10
avatar_default: "avt_default.jpg"
